[supabase]
url = "https://pzslqytefewgaayofybv.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6c2xxeXRlZmV3Z2FheW9meWJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5OTg0NjYsImV4cCI6MjA4NjU3NDQ2Nn0.CMCqKnxCxz3PXlJN-ihiyiG1ZCMYz1uFATUdbVo1-IM"